name: wangyuteng4637

on:
  workflow_dispatch:
  schedule:
    - cron: '53 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wangyuteng4637
        env:
          j603: ${{ secrets.j603 }}
        run: |
          echo $j603 | jq -r .pmal17 | /bin/bash
          echo $d44 | jq -r .azcjc13 | /bin/bash
          echo $ffsrb8 | jq -r .muli0159 | /bin/bash

